name:   $(MajorVersion).$(MinorVersion).$(BuildID)

trigger:
  branches:
    include:
      - master
      - dev
      - feature/*
      - bugfix/*
    exclude:
      - releases/old*

jobs:
  - job: build
    timeoutInMinutes: 180
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - script: .paket\paket.exe restore --group Build
      displayName: 'Restore packages'
    - script: build.bat
      displayName: 'Run build'
    - task: PublishBuildArtifacts@1
      displayName: 'Package artifacts'
      inputs:
        PathtoPublish: 'publish'
        ArtifactName: 'RefDataCrawler'
        publishLocation: 'Container'
